apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockube-arpita
spec:
  replicas: 2
  selector:
      matchLabels:
        app: dockube-arpita
  template:
    metadata:
      labels:
        app: dockube-arpita
    spec:
      containers:
      - name: dockube-arpita-pod
        image: arpitagupta19/dockube_arpita
        ports: 
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: dockube-arpita-service
spec:
  selector:
    app: dockube-arpita
  ports:
  - name: http
    protocol: TCP
    port: 2000
    targetPort: 2000
  type: LoadBalancer
